Expose certain parameters to config
int-brain-lab/ibl-sorter pull request #19
Opened 2024-08-12 15:53 UTC by chris-langfield

2024-08-16 14:59 UTC, chris-langfield commented
Tests and integration test pass on server with 

`sudo ./.venv/bin/python examples/integration_100s.py server` from repo directory.

2024-08-20 10:11 UTC, oliche commented on examples/integration_100s.py
Yes we'll do better than that but it's good enough for now !

2024-08-20 10:15 UTC, oliche commented on iblsorter/main.py
> +    ctx.motion_params = motion_params
Here I probably would have added the new parameters groups in a Nested structure. 
This is possible with Pydantic and we would have something like:

params:
- ... old params
- preprocessing
- registration

2024-08-20 10:16 UTC, oliche commented on iblsorter/params.py
Yes this is exactly the spirit of nested parameters ! :smiley:

2024-08-20 10:17 UTC, oliche requested changes
This is good, however we probably need to add the parameters for the bad channel detection right ? 
I can help with that and keep committing to this branch

2024-08-28 16:11 UTC, merged